apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
      httpMethod: POST
      timeInterval: 1s
      maxLines: 10000
      minInterval: 1s
    readOnly: false