{
 "title": "🔥 Cardly",
 "tags": [
  "app",
  "system",
  "monitoring"
 ],
 "time": { "from": "2025-05-25T15:28:11.694Z", "to": "2025-05-26T03:28:11.694Z" },
 "refresh": "10s",
 "panels": [
  { "title": "Аналитика по авторизации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "📈 Продолжительность регистрации",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "auth_register_duration_seconds" }
   ]
  },
  {
   "title": "🔐 Статистика аутентификации",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_register_attempt_total" },
    { "expr": "auth_register_conflict_total" },
    { "expr": "auth_register_failure_total" }
   ]
  },
  { "title": "Аналитика машины", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Время готовности приложения",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_ready_time_seconds" }
   ]
  },
  {
   "title": "🚀 Время запуска приложения",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds"
    }
   ]
  },
  {
   "title": "🔥 Использование процессора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage" },
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "🕒 Время работы процесса",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_uptime_seconds{job=\"app\", instance=\"app:8080\"})"
    }
   ]
  },
  {
   "title": "📊 Активные HTTP-запросы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds"
    }
   ]
  },
  {
   "title": "🌐 Время обработки HTTP-запросов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "http_server_requests_seconds" }
   ]
  }
 ]
}